### ISSUE TITLE
Document source of deep dive information

### ISSUE THREAD

**Issue by trumank** [MoritzHayden/drg-api#21]
It is not clear where the deep dive information is coming from (sourced from running the game locally? from a reimplementation of the generation logic? crowd sourced or pulled from another service?)

**Comment by MoritzHayden** [comment]
Take a look at #4

**Comment by trumank** [comment]
> Take a look at #4

According to this issue, this spreadsheet is currently the primary (and only) source of deep dive information? I understand drg-api serves a purpose as an aggregator and provider of stable endpoints, but the primary sources should be disclosed and given proper attribution.
